spring:
  application:
    name: intelligent-code-app
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: local
server:
  port: ${PORT}
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wzh.intelligentcodeapp.controller

langchain4j:
  open-ai:
    chat-model:
      api-key: ${ALI_YUN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus
      timeout: 600s
      log-requests: true
      log-responses: true
      # 是否严格检查json
      strict-json-schema: true
    streaming-chat-model:
      api-key: ${ALI_YUN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus
      timeout: 600s
      log-requests: true
      log-responses: true