spring:
  application:
    name: intelligent-code-app
server:
  port: 8081
  servlet:
    context-path: /api


# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wzh.intelligentcodeapp.controller
